---
name: Unit Tests

on:
  pull_request:
    paths:
      - .github/workflows/unit-tests.yml
      - lib/**
      - tests/**

defaults:
  run:
    shell: sh

jobs:
  unit-tests-all:
    name: All
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v5
      - name: Run tests
        run: make test
